#!/usr/bin/env python3
"""Mathematical certificates for exact-two-solution Sudoku instances.

The module is deliberately independent of the neural solver.  It checks the
combinatorial statements used by the Hybrid+C5 explainability experiments:

* clues lie in the agreement set of the two certified solutions;
* every affected unit induces non-trivial symbol cycles;
* the two difference legs form a four-colour exact-cover bitrade graph;
* exact-two instances have a connected (indecomposable) trade graph;
* four-cell differences are alternating rectangles in two boxes;
* a standard Sudoku stabilizer either fixes both solutions or swaps them.

The stabilizer search is exhaustive for the explicitly documented standard
group generated by band/stack preserving row/column permutations,
transposition, and global digit relabeling.  It does not silently identify an
abstract A/B label swap with a Sudoku automorphism.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import hashlib
import itertools
import math
from typing import Iterable, Iterator

import numpy as np


SCHEMA_VERSION = "two_solution_explainability/v1"


@dataclass(frozen=True)
class SudokuSpec:
    """Standard square-box Sudoku specification."""

    box_size: int

    @property
    def n(self) -> int:
        return self.box_size * self.box_size

    @property
    def cell_count(self) -> int:
        return self.n * self.n


@dataclass(frozen=True)
class BacktrackingEnumeration:
    solutions: tuple[np.ndarray, ...]
    nodes: int
    exhausted: bool
    solution_cap_hit: bool


def _grid(value: Iterable[int] | np.ndarray, spec: SudokuSpec) -> np.ndarray:
    result = np.asarray(value, dtype=np.int16)
    if result.size != spec.cell_count:
        raise ValueError(
            f"Expected {spec.cell_count} cells for N={spec.n}, got {result.size}"
        )
    return result.reshape(spec.n, spec.n)


def array_sha256(value: np.ndarray) -> str:
    array = np.ascontiguousarray(value)
    payload = (
        str(array.shape).encode("ascii")
        + b"|"
        + str(array.dtype).encode("ascii")
        + b"|"
        + array.tobytes()
    )
    return hashlib.sha256(payload).hexdigest()


def compact_grid_key(value: np.ndarray) -> bytes:
    return np.asarray(value, dtype=np.uint8).reshape(-1).tobytes()


def unordered_pair_sha256(solution_a: np.ndarray, solution_b: np.ndarray) -> str:
    keys = sorted((compact_grid_key(solution_a), compact_grid_key(solution_b)))
    return hashlib.sha256(keys[0] + b"|" + keys[1]).hexdigest()


def valid_completed_grid(value: np.ndarray, spec: SudokuSpec) -> bool:
    grid = _grid(value, spec)
    target = np.arange(1, spec.n + 1)
    for row in range(spec.n):
        if not np.array_equal(np.sort(grid[row]), target):
            return False
    for col in range(spec.n):
        if not np.array_equal(np.sort(grid[:, col]), target):
            return False
    q = spec.box_size
    for box_row in range(0, spec.n, q):
        for box_col in range(0, spec.n, q):
            box = grid[box_row : box_row + q, box_col : box_col + q]
            if not np.array_equal(np.sort(box.reshape(-1)), target):
                return False
    return True


def clue_consistent(puzzle: np.ndarray, solution: np.ndarray, spec: SudokuSpec) -> bool:
    puzzle_grid = _grid(puzzle, spec)
    solution_grid = _grid(solution, spec)
    return bool(np.all((puzzle_grid == 0) | (puzzle_grid == solution_grid)))


def standard_units(spec: SudokuSpec) -> list[tuple[str, int, tuple[int, ...]]]:
    n = spec.n
    q = spec.box_size
    result: list[tuple[str, int, tuple[int, ...]]] = []
    for row in range(n):
        result.append(("row", row, tuple(row * n + col for col in range(n))))
    for col in range(n):
        result.append(("column", col, tuple(row * n + col for row in range(n))))
    for box_row in range(q):
        for box_col in range(q):
            cells = tuple(
                (box_row * q + within_row) * n + (box_col * q + within_col)
                for within_row in range(q)
                for within_col in range(q)
            )
            result.append(("box", box_row * q + box_col, cells))
    return result


def _canonical_directed_cycle(cycle: list[int]) -> tuple[int, ...]:
    start = min(range(len(cycle)), key=cycle.__getitem__)
    return tuple(cycle[start:] + cycle[:start])


def unit_cycle_audit(
    solution_a: np.ndarray, solution_b: np.ndarray, spec: SudokuSpec
) -> list[dict[str, object]]:
    a = _grid(solution_a, spec).reshape(-1)
    b = _grid(solution_b, spec).reshape(-1)
    records: list[dict[str, object]] = []
    for kind, unit_index, cells in standard_units(spec):
        mapping = np.zeros(spec.n + 1, dtype=np.int16)
        for cell in cells:
            source = int(a[cell])
            target = int(b[cell])
            if mapping[source] not in (0, target):
                raise AssertionError("A unit did not induce a symbol function")
            mapping[source] = target
        if set(mapping[1:].tolist()) != set(range(1, spec.n + 1)):
            raise AssertionError("Unit symbol map was not a permutation")

        cycles: list[tuple[int, ...]] = []
        seen: set[int] = set()
        for digit in range(1, spec.n + 1):
            if digit in seen:
                continue
            current = digit
            cycle: list[int] = []
            while current not in seen:
                seen.add(current)
                cycle.append(current)
                current = int(mapping[current])
            if len(cycle) > 1:
                cycles.append(_canonical_directed_cycle(cycle))
        difference_cells = [cell for cell in cells if a[cell] != b[cell]]
        if len(difference_cells) == 1:
            raise AssertionError("An affected Sudoku unit differed in exactly one cell")
        records.append(
            {
                "kind": kind,
                "unit_index": unit_index,
                "difference_count": len(difference_cells),
                "difference_cells": difference_cells,
                "nontrivial_cycles": [list(cycle) for cycle in cycles],
            }
        )
    return records


class _DisjointSet:
    def __init__(self, size: int):
        self.parent = list(range(size))
        self.rank = [0] * size

    def find(self, value: int) -> int:
        while self.parent[value] != value:
            self.parent[value] = self.parent[self.parent[value]]
            value = self.parent[value]
        return value

    def union(self, left: int, right: int) -> None:
        left_root = self.find(left)
        right_root = self.find(right)
        if left_root == right_root:
            return
        if self.rank[left_root] < self.rank[right_root]:
            left_root, right_root = right_root, left_root
        self.parent[right_root] = left_root
        if self.rank[left_root] == self.rank[right_root]:
            self.rank[left_root] += 1


def _assignment_constraints(
    row: int, col: int, digit: int, spec: SudokuSpec
) -> tuple[tuple[object, ...], ...]:
    box = (row // spec.box_size) * spec.box_size + col // spec.box_size
    return (
        ("cell", row, col),
        ("row_digit", row, digit),
        ("column_digit", col, digit),
        ("box_digit", box, digit),
    )


def exact_cover_trade_audit(
    solution_a: np.ndarray, solution_b: np.ndarray, spec: SudokuSpec
) -> dict[str, object]:
    a = _grid(solution_a, spec)
    b = _grid(solution_b, spec)
    difference = np.argwhere(a != b)
    delta = len(difference)
    if delta == 0:
        raise ValueError("The two solutions are identical")

    constraints: dict[tuple[object, ...], list[tuple[str, int]]] = {}
    vertex_constraints: dict[tuple[str, int], list[tuple[object, ...]]] = {}
    for leg, grid in (("A", a), ("B", b)):
        for index, (row, col) in enumerate(difference.tolist()):
            vertex = (leg, index)
            items = list(
                _assignment_constraints(row, col, int(grid[row, col]), spec)
            )
            vertex_constraints[vertex] = items
            for constraint in items:
                constraints.setdefault(constraint, []).append(vertex)

    edges: list[tuple[int, int, str, tuple[object, ...]]] = []
    degree = np.zeros(2 * delta, dtype=np.int16)
    colour_count = {
        (leg, index): {colour: 0 for colour in ("cell", "row_digit", "column_digit", "box_digit")}
        for leg in ("A", "B")
        for index in range(delta)
    }
    dsu = _DisjointSet(2 * delta)
    for constraint, endpoints in constraints.items():
        if len(endpoints) != 2 or {item[0] for item in endpoints} != {"A", "B"}:
            raise AssertionError(
                f"Trade constraint {constraint!r} did not have one endpoint per leg"
            )
        left_vertex = endpoints[0] if endpoints[0][0] == "A" else endpoints[1]
        right_vertex = endpoints[1] if endpoints[1][0] == "B" else endpoints[0]
        left = left_vertex[1]
        right = delta + right_vertex[1]
        colour = str(constraint[0])
        edges.append((left, right, colour, constraint))
        degree[left] += 1
        degree[right] += 1
        colour_count[left_vertex][colour] += 1
        colour_count[right_vertex][colour] += 1
        dsu.union(left, right)

    degree_four = bool(np.all(degree == 4))
    colours_once = all(
        all(count == 1 for count in counts.values())
        for counts in colour_count.values()
    )
    if not degree_four or not colours_once:
        raise AssertionError("Exact-cover trade graph was not four-regular by colour")

    components: dict[int, list[int]] = {}
    for vertex in range(2 * delta):
        components.setdefault(dsu.find(vertex), []).append(vertex)
    ordered_components = sorted((sorted(values) for values in components.values()))
    edge_payload = "\n".join(
        repr(item) for item in sorted(edges, key=lambda edge: repr(edge[3]))
    ).encode("utf-8")
    return {
        "red_size": delta,
        "blue_size": delta,
        "vertex_count": 2 * delta,
        "edge_count": len(edges),
        "degree_four_verified": degree_four,
        "edge_colour_matchings_verified": colours_once,
        "component_count": len(ordered_components),
        "component_sizes": [len(values) for values in ordered_components],
        "connected": len(ordered_components) == 1,
        "graph_sha256": hashlib.sha256(edge_payload).hexdigest(),
    }


def four_cell_rectangle_audit(
    solution_a: np.ndarray, solution_b: np.ndarray, spec: SudokuSpec
) -> dict[str, object] | None:
    a = _grid(solution_a, spec)
    b = _grid(solution_b, spec)
    difference = np.argwhere(a != b)
    if len(difference) != 4:
        return None
    rows, row_counts = np.unique(difference[:, 0], return_counts=True)
    cols, col_counts = np.unique(difference[:, 1], return_counts=True)
    boxes = np.asarray(
        [
            (row // spec.box_size) * spec.box_size + col // spec.box_size
            for row, col in difference.tolist()
        ],
        dtype=np.int16,
    )
    unique_boxes, box_counts = np.unique(boxes, return_counts=True)
    digits = np.unique(a[a != b])
    support_ok = (
        len(rows) == 2
        and np.array_equal(np.sort(row_counts), np.asarray([2, 2]))
        and len(cols) == 2
        and np.array_equal(np.sort(col_counts), np.asarray([2, 2]))
        and len(unique_boxes) == 2
        and np.array_equal(np.sort(box_counts), np.asarray([2, 2]))
        and len(digits) == 2
    )
    alternating = support_ok
    if alternating:
        sub_a = a[np.ix_(rows, cols)]
        sub_b = b[np.ix_(rows, cols)]
        alternating = bool(
            sub_a[0, 0] == sub_a[1, 1]
            and sub_a[0, 1] == sub_a[1, 0]
            and sub_a[0, 0] != sub_a[0, 1]
            and np.array_equal(sub_b, sub_a[::-1])
        )
    if not alternating:
        raise AssertionError("A four-cell solution difference was not an alternating rectangle")
    return {
        "verified": True,
        "rows": rows.astype(int).tolist(),
        "columns": cols.astype(int).tolist(),
        "boxes": unique_boxes.astype(int).tolist(),
        "digits": digits.astype(int).tolist(),
    }


@lru_cache(maxsize=None)
def block_preserving_permutations(box_size: int) -> tuple[tuple[int, ...], ...]:
    """Return old-index-at-new-index permutations preserving bands/stacks."""
    q = int(box_size)
    result: set[tuple[int, ...]] = set()
    for block_order in itertools.permutations(range(q)):
        for within_orders in itertools.product(
            itertools.permutations(range(q)), repeat=q
        ):
            order: list[int] = []
            for old_block in block_order:
                order.extend(
                    old_block * q + within
                    for within in within_orders[old_block]
                )
            result.add(tuple(order))
    expected = math.factorial(q) ** (q + 1)
    if len(result) != expected:
        raise AssertionError("Unexpected block-preserving permutation count")
    return tuple(sorted(result))


def transform_standard_grid(
    grid: np.ndarray,
    *,
    row_order: Iterable[int],
    column_order: Iterable[int],
    digit_map: Iterable[int],
    transpose: bool,
) -> np.ndarray:
    result = np.asarray(grid)
    if transpose:
        result = result.T
    result = result[np.asarray(tuple(row_order), dtype=np.int16)]
    result = result[:, np.asarray(tuple(column_order), dtype=np.int16)]
    mapping = np.asarray(tuple(digit_map), dtype=np.int16)
    return mapping[result]


def _infer_digit_map(position_grid: np.ndarray, target_grid: np.ndarray, n: int) -> np.ndarray | None:
    mapping = np.zeros(n + 1, dtype=np.int16)
    for source, target in zip(position_grid.reshape(-1), target_grid.reshape(-1)):
        source_int = int(source)
        target_int = int(target)
        if source_int <= 0 or target_int <= 0:
            raise ValueError("Digit maps must be inferred from complete solutions")
        if mapping[source_int] == 0:
            mapping[source_int] = target_int
        elif mapping[source_int] != target_int:
            return None
    if set(mapping[1:].tolist()) != set(range(1, n + 1)):
        return None
    return mapping


def _position_mask_stabilizers(
    puzzle: np.ndarray, spec: SudokuSpec
) -> Iterator[tuple[bool, tuple[int, ...], tuple[int, ...]]]:
    target = _grid(puzzle, spec) > 0
    orders = np.asarray(block_preserving_permutations(spec.box_size), dtype=np.int16)
    target_row_counts = target.sum(axis=1)
    for transpose in (False, True):
        source = target.T if transpose else target
        source_row_counts = source.sum(axis=1)
        row_matches = np.all(
            source_row_counts[orders] == target_row_counts[None, :], axis=1
        )
        for row_order_array in orders[row_matches]:
            reordered = source[row_order_array]
            # Shape: rows x candidate-column-orders x destination-columns.
            transformed = reordered[:, orders].transpose(1, 0, 2)
            column_matches = np.flatnonzero(
                np.all(transformed == target[None, :, :], axis=(1, 2))
            )
            for column_index in column_matches.tolist():
                yield (
                    transpose,
                    tuple(int(x) for x in row_order_array),
                    tuple(int(x) for x in orders[column_index]),
                )


def standard_pair_automorphism_audit(
    puzzle: np.ndarray,
    solution_a: np.ndarray,
    solution_b: np.ndarray,
    spec: SudokuSpec,
    *,
    witness_limit: int = 8,
) -> dict[str, object]:
    """Exhaustively audit the pair action of the documented standard group."""
    puzzle_grid = _grid(puzzle, spec)
    a = _grid(solution_a, spec)
    b = _grid(solution_b, spec)
    fix_count = 0
    swap_count = 0
    position_candidates = 0
    witnesses: list[dict[str, object]] = []
    for transpose, row_order, column_order in _position_mask_stabilizers(
        puzzle_grid, spec
    ):
        position_candidates += 1
        positioned_a = a.T if transpose else a
        positioned_a = positioned_a[np.asarray(row_order)][:, np.asarray(column_order)]
        for action, target in (("fix", a), ("swap", b)):
            digit_map = _infer_digit_map(positioned_a, target, spec.n)
            if digit_map is None:
                continue
            transformed_puzzle = transform_standard_grid(
                puzzle_grid,
                row_order=row_order,
                column_order=column_order,
                digit_map=digit_map,
                transpose=transpose,
            )
            if not np.array_equal(transformed_puzzle, puzzle_grid):
                continue
            transformed_a = transform_standard_grid(
                a,
                row_order=row_order,
                column_order=column_order,
                digit_map=digit_map,
                transpose=transpose,
            )
            transformed_b = transform_standard_grid(
                b,
                row_order=row_order,
                column_order=column_order,
                digit_map=digit_map,
                transpose=transpose,
            )
            expected_a, expected_b = (a, b) if action == "fix" else (b, a)
            if not (
                np.array_equal(transformed_a, expected_a)
                and np.array_equal(transformed_b, expected_b)
            ):
                raise AssertionError("A claimed pair action failed its witness check")
            if action == "fix":
                fix_count += 1
            else:
                swap_count += 1
            if len(witnesses) < witness_limit:
                witnesses.append(
                    {
                        "action": action,
                        "transpose": transpose,
                        "row_order": list(row_order),
                        "column_order": list(column_order),
                        "digit_map": digit_map.astype(int).tolist(),
                    }
                )
    stabilizer_size = fix_count + swap_count
    if stabilizer_size == 0:
        raise AssertionError("The identity transformation was not found")
    if swap_count and fix_count != swap_count:
        raise AssertionError("Swap elements must form a coset of the pair-action kernel")
    return {
        "group_convention": (
            "standard_band_stack_row_column_transpose_and_global_digit_relabel"
        ),
        "stabilizer_certified": True,
        "position_mask_stabilizers_checked": position_candidates,
        "stabilizer_size": stabilizer_size,
        "kernel_size": fix_count,
        "rho_image_size": 2 if swap_count else 1,
        "swap_exists": bool(swap_count),
        "swap_count": swap_count,
        "regime": (
            "stabilizer_swap_certified"
            if swap_count
            else "local_trade_no_swap_certified"
        ),
        "witnesses": witnesses,
    }


def solution_orientations(
    solution_a: np.ndarray, solution_b: np.ndarray
) -> dict[str, object]:
    a = np.asarray(solution_a).reshape(-1)
    b = np.asarray(solution_b).reshape(-1)
    indices = np.flatnonzero(a != b)
    if not len(indices):
        raise ValueError("The solutions are identical")
    first = int(indices[0])
    return {
        "source_a_defined": True,
        "first_difference_cell": first,
        "a_is_low_at_first_difference": bool(a[first] < b[first]),
        "a_is_lexicographically_first": bool(tuple(a.tolist()) < tuple(b.tolist())),
    }


def audit_instance(
    puzzle: np.ndarray,
    solution_a: np.ndarray,
    solution_b: np.ndarray,
    spec: SudokuSpec,
    *,
    exact_two_certified: bool,
    symmetry: dict[str, object] | None = None,
    provenance: dict[str, object] | None = None,
) -> dict[str, object]:
    puzzle_grid = _grid(puzzle, spec)
    a = _grid(solution_a, spec)
    b = _grid(solution_b, spec)
    if not valid_completed_grid(a, spec) or not valid_completed_grid(b, spec):
        raise AssertionError("A or B was not a valid completed Sudoku grid")
    if not clue_consistent(puzzle_grid, a, spec) or not clue_consistent(
        puzzle_grid, b, spec
    ):
        raise AssertionError("A clue was not in the A/B agreement set")
    difference_mask = a != b
    difference_cells = np.flatnonzero(difference_mask.reshape(-1)).astype(int).tolist()
    if not difference_cells:
        raise AssertionError("The claimed two solutions were identical")
    unit_audit = unit_cycle_audit(a, b, spec)
    trade = exact_cover_trade_audit(a, b, spec)
    if exact_two_certified and not trade["connected"]:
        raise AssertionError(
            "Exact-two certification contradicted the trade-component theorem"
        )
    rectangle = four_cell_rectangle_audit(a, b, spec)
    symmetry_payload = symmetry or {
        "group_convention": (
            "standard_band_stack_row_column_transpose_and_global_digit_relabel"
        ),
        "stabilizer_certified": False,
        "stabilizer_size": None,
        "kernel_size": None,
        "rho_image_size": None,
        "swap_exists": None,
        "regime": "local_trade_swap_unknown",
        "witnesses": [],
    }
    sample_hash = hashlib.sha256(
        compact_grid_key(puzzle_grid)
        + b"|"
        + unordered_pair_sha256(a, b).encode("ascii")
    ).hexdigest()
    return {
        "schema_version": SCHEMA_VERSION,
        "sample_id": sample_hash,
        "board_order": spec.box_size,
        "grid_size": spec.n,
        "puzzle_sha256": array_sha256(puzzle_grid.astype(np.uint8)),
        "solution_a_sha256": array_sha256(a.astype(np.uint8)),
        "solution_b_sha256": array_sha256(b.astype(np.uint8)),
        "unordered_pair_sha256": unordered_pair_sha256(a, b),
        "solution_certification": {
            "exact_two_certified": bool(exact_two_certified),
            "solutions_exactly_ab": bool(exact_two_certified),
        },
        "difference": {
            "cell_indices": difference_cells,
            "size": len(difference_cells),
            "all_clues_in_agreement": True,
            "unit_cycles": unit_audit,
            "four_cell_rectangle": rectangle,
        },
        "exact_cover_trade": {
            **trade,
            "minimal_unavoidable_certified": bool(exact_two_certified),
        },
        "orientations": solution_orientations(a, b),
        "symmetry": symmetry_payload,
        "provenance": provenance or {},
    }


def enumerate_backtracking_solutions(
    puzzle: np.ndarray,
    spec: SudokuSpec,
    *,
    max_solutions: int = 3,
    random_seed: int | None = None,
) -> BacktrackingEnumeration:
    """Independent MRV bit-mask enumerator used to cross-check DLX data."""
    grid = _grid(puzzle, spec).astype(np.int16, copy=True)
    n = spec.n
    full = (1 << n) - 1
    row_used = [0] * n
    column_used = [0] * n
    box_used = [0] * n
    empties: list[tuple[int, int]] = []
    for row in range(n):
        for col in range(n):
            value = int(grid[row, col])
            box = (row // spec.box_size) * spec.box_size + col // spec.box_size
            if value == 0:
                empties.append((row, col))
                continue
            if not 1 <= value <= n:
                raise ValueError(f"Invalid clue {value}")
            bit = 1 << (value - 1)
            if row_used[row] & bit or column_used[col] & bit or box_used[box] & bit:
                return BacktrackingEnumeration((), 0, True, False)
            row_used[row] |= bit
            column_used[col] |= bit
            box_used[box] |= bit

    rng = np.random.default_rng(random_seed) if random_seed is not None else None
    solutions: list[np.ndarray] = []
    nodes = 0
    cap_hit = False

    def candidates(row: int, col: int) -> int:
        box = (row // spec.box_size) * spec.box_size + col // spec.box_size
        return full & ~(row_used[row] | column_used[col] | box_used[box])

    def search(remaining: list[tuple[int, int]]) -> bool:
        nonlocal nodes, cap_hit
        if not remaining:
            solutions.append(grid.copy().astype(np.uint8))
            if len(solutions) >= max_solutions:
                cap_hit = True
                return True
            return False
        best_index = -1
        best_mask = 0
        best_count = n + 1
        for index, (row, col) in enumerate(remaining):
            mask = candidates(row, col)
            count = int(mask.bit_count())
            if count == 0:
                return False
            if count < best_count:
                best_index = index
                best_mask = mask
                best_count = count
                if count == 1:
                    break
        row, col = remaining[best_index]
        rest = remaining[:best_index] + remaining[best_index + 1 :]
        digits = [digit for digit in range(1, n + 1) if best_mask & (1 << (digit - 1))]
        if rng is not None:
            rng.shuffle(digits)
        box = (row // spec.box_size) * spec.box_size + col // spec.box_size
        for digit in digits:
            nodes += 1
            bit = 1 << (digit - 1)
            grid[row, col] = digit
            row_used[row] |= bit
            column_used[col] |= bit
            box_used[box] |= bit
            stop = search(rest)
            row_used[row] ^= bit
            column_used[col] ^= bit
            box_used[box] ^= bit
            grid[row, col] = 0
            if stop:
                return True
        return False

    stopped_early = search(empties)
    return BacktrackingEnumeration(
        solutions=tuple(solutions),
        nodes=nodes,
        exhausted=not stopped_early,
        solution_cap_hit=cap_hit,
    )


def exact_solution_pair(
    enumeration: BacktrackingEnumeration,
    solution_a: np.ndarray,
    solution_b: np.ndarray,
) -> bool:
    expected = {compact_grid_key(solution_a), compact_grid_key(solution_b)}
    actual = {compact_grid_key(solution) for solution in enumeration.solutions}
    return (
        enumeration.exhausted
        and not enumeration.solution_cap_hit
        and len(enumeration.solutions) == 2
        and actual == expected
    )
